{% set version = "1.1.10" %}

package:
    name: setproctitle
    version: {{ version }}

source:
    fn: setproctitle-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/s/setproctitle/setproctitle-{{ version }}.tar.gz
    md5: 2dcdd1b761700a5a13252fea3dfd1977

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
    run:
        - python

test:
    imports:
        - setproctitle

about:
    home: http://code.google.com/p/py-setproctitle/
    license: BSD License
    summary: 'A library to allow customization of the process title.'

extra:
    recipe-maintainers:
        - pelson
        - ocefpaf
        - scopatz
