{% set name = "setproctitle" %}
{% set version = "1.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/setproctitle-{{ version }}.tar.gz
  sha256: b9fb97907c830d260fa0658ed58afd48a86b2b88aac521135c352ff7fd3477fd

build:
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv
  number: 2

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - setproctitle
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dvarrazzo/py-setproctitle
  summary: A Python module to customize the process title
  license: BSD-3-Clause
  license_file:
    - COPYRIGHT

extra:
  recipe-maintainers:
    - pelson
    - ocefpaf
    - scopatz
