{% set version = "1.2.1" %}

package:
  name: setproctitle
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/setproctitle/setproctitle-{{ version }}.tar.gz
  sha256: 5f0eecb27815e31799a69eb6a06b4d375d38887d079d410565b0be82da65c950

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - setproctitle

about:
  home: http://code.google.com/p/py-setproctitle/
  license: BSD 3-clause
  license_file: COPYRIGHT
  license_family: BSD
  summary: A library to allow customization of the process title.

extra:
  recipe-maintainers:
    - pelson
    - ocefpaf
    - scopatz
