{% set name = "setproctitle" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/setproctitle-{{ version }}.tar.gz
  sha256: ff0facafbe4e4e3b336814ffee99e41b4d6065f512cf5616e0a1bf689aca2af6

build:
  skip: true  # [py<37]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

test:
  imports:
    - setproctitle
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://code.google.com/p/py-setproctitle/
  license: BSD-3-Clause
  license_file: COPYRIGHT
  license_family: BSD
  summary: A Python module to customize the process title

extra:
  recipe-maintainers:
    - pelson
    - ocefpaf
    - scopatz
