{% set name = "setproctitle" %}
{% set version = "1.3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/setproctitle-{{ version }}.tar.gz
  sha256: c9f32b96c700bb384f33f7cf07954bb609d35dd82752cef57fb2ee0968409169

build:
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools
    - pip
  run:
    - python

test:
  imports:
    - setproctitle
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dvarrazzo/py-setproctitle
  summary: A Python module to customize the process title
  license: BSD-3-Clause
  license_file:
    - COPYRIGHT

extra:
  recipe-maintainers:
    - pelson
    - ocefpaf
    - scopatz
