context:
  version: 1.3.7

package:
  name: setproctitle
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/setproctitle-{{ version }}.tar.gz
  sha256: bc2bc917691c1537d5b9bca1468437176809c7e11e5694ca79a9ca12345dcb9e

build:
  script: ${{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
  host:
    - python
    - setuptools
    - pip
  run:
    - python

tests:
 - python:
    imports:
      - setproctitle
    pip_check: true

about:
  homepage: https://github.com/dvarrazzo/py-setproctitle
  summary: A Python module to customize the process title
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pelson
    - ocefpaf
    - scopatz
