appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default}
travis:
  secure: {BINSTAR_TOKEN: 1AR5sdujqgj/Jyy3upNAsKRcFFu9MQIHDo1SHTQuuapUgnW+604I5NY6bmId1m/phtNUVLLUYbBrUyh6VF+PZGvQt/Z1VV+VaR70xpZjCACCO8cGxyfTmD97xOpGeNIaPwVxXKmavD3HsQhq7cACD63THlwmvC4QjpxOdIEndaawJmExp++uMCOq1mMfnh39ZKAS4suc5tHj8L+km4j/Cnv215bTb/dQW+K/Dkbk8eVxaQHMcfcFiDohdu8BFKXnGyGh3Ci+D1jcG9a5B5d1Ww2x1cLG0u2xee/kqJHAuiFiho423rK01DOMlyosaSj4KraZz8Xg3bjqS5lCdtnVyqJu2YbWrgxIK4ZxavN2hIpL2IEqz9vbntiTofRk5pm6TLOiGl3qAqggXdXI23/UJANsy/p9z0r8GYr65VYeHumAq1696umrdsbMmDC7dESNHN6+cI5vM30C6Y7RUnOvsZNsaveZTxI9tuiA4Uit50xif3AEg+dI809zgsNWXWtnL/ccTOv6bDurK10goj3l6gUWuFTKToTQ0m9JYNEh7Tv3BW2qe93Cod+QHWEJysr9VucOn0YNLQJIrM2p9h8icFuKm9cPL2Jt9Q06akHFe9XD0WY83PhAv6Vdqs6wbaTJsd8q/B4LF9yQVzVyTBft8QLxkg6hYya+kHMuuFnHTX8=}
